export const productos = [
    {
        id: 1,
        img: 'https://eldiariony.com/wp-content/uploads/sites/2/2022/09/Hamburguesa-con-queso-shutterstock_215936923.jpg?quality=75&strip=all&w=1200',
        title: 'Extreme Burguer',
        description: 'Hamburguesa con doble carne, doble cheddar, doble bacon, cebolla crispy y salsa barbacoa.',
        price: 2500,
        quantity: 1,
        promotion: true,
        off: 70,
    },
    {
        id: 2,
        img: 'https://www.portablepress.com/wp-content/uploads/2017/10/Fast-food-combo-meal-1.jpg',
        title: 'Combo Big Burguer',
        description: 'Hamburguesa con doble carne, doble chedar, lechuga, tomate. Salsa a eleccion. Papas y bebida.',
        price: 1800,
        quantity: 1,
        promotion: true,
        off: 50,
    },
    {
        id: 3,
        img: 'https://todoenuno.app/wp-content/uploads/2022/04/Hamburguesas-2.jpg',
        title: 'Hamburguesa Simple',
        description: 'Hamburguesa simple de carne, lechuga, tomate, queso y salsa barbacoa.',
        price: 1000,
        quantity: 1,
        promotion: true,
        off: 30,
    },
    {
        id: 4,
        img: 'http://d3lp4xedbqa8a5.cloudfront.net/s3/digital-cougar-assets/GourmetTraveller/2013/05/08/4166/0511GT-TO-pizza-caprese-628.jpg?width=768&height=639&mode=crop&quality=75&anchor=middlecenter',
        title: 'Pizza Caprese 6 Porciones',
        description: 'Pizza con salsa de tomate, queso, rodajas de tomate cherry y albahaca.',
        price: 1200,
        quantity: 1,
        promotion: false,
        off: 0,
    },
    {
        id: 5,
        img: 'https://morixe.com.ar/files/recetas/thumbs/papascheddarmorixe03.jpg',
        title: 'Papas Fritas',
        description: 'Porcion mediana de papas fritas con bacon y queso chedar.',
        price: 850,
        quantity: 1,
        promotion: false,
        off: 0,
    },
    {
        id: 6,
        img: 'https://st3.depositphotos.com/3028293/15315/i/600/depositphotos_153159806-stock-photo-chicken-nuggets-and-french-fries.jpg',
        title: 'Nuggets de Pollo',
        description: 'Porcion de 10 nuggets de pollo, con dos salsas a eleccion y papas fritas.',
        price: 1500,
        quantity: 1,
        promotion: false,
        off: 0,
    },
]